version: '3'

services:
  
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/
    ports:
      - "443:443"
    networks:
      - custom-network
    volumes:
      - wordpress-files:/var/www/html
      - nginx-conf:/etc/nginx/conf.d
    restart: on-failure

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress/
    networks:
      - custom-network
    volumes:
      - wordpress-files:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
      - WORDPRESS_DB_NAME=${DB_NAME}
    restart: on-failure

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
    networks:
      - custom-network
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    restart: on-failure

networks:
  custom-network:
    driver: bridge

volumes:
  wordpress-files:
  wordpress-db:
  mariadb-data:
  nginx-conf:

