services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        - DB_NAME=$DB_NAME
        - DB_USER=$DB_USER
        - DB_USER_PASSWORD=$DB_USER_PASSWORD
        - DB_ROOT_PASSWORD=$DB_ROOT_PASSWORD

    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: on-failure
    ports:
      - 3306:3306

  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - 443:443
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
      args:
        - DOMAIN_NAME=$DOMAIN_NAME
        - DB_NAME= $DB_NAME
        - DB_USER=$DB_USER
        - DB_HOST=$DB_HOST
        - DB_USER_PASSWORD=$DB_USER_PASSWORD
        - WP_ADMIN=$WP_ADMIN
        - WP_ADMIN_PASSWORD=$WP_ADMIN_PASSWORD
        - WP_USER=$WP_USER
        - WP_USER_PASSWORD=$WP_USER_PASSWORD
        
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart: on-failure
    ports:
      - 9000:9000

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/joakoeni/test/data/wordpress"

  mariadb:
    driver_opts:
      type: none
      o: bind
      device: "/home/joakoeni/test/data/mariadb"

networks:
  inception:
    driver: bridge
